version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lbanblog
    restart: unless-stopped
    env_file: .env
    # environment:
    #   - MONGO_USERNAME=$MONGO_USERNAME
    #   - MONGO_PASSWORD=$MONGO_PASSWORD
    #   - MONGO_HOSTNAME=db
    #   - MONGO_PORT=$MONGO_PORT
    #   - MONGO_DB=$MONGO_DB 
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
    ports:
      - 80:8080
    networks:
      - app-network
    # command: bash -c /usr/src/app/start.sh
    # command: bash -c /usr/src/app/config/start.sh
    command: /home/node/app/node_modules/.bin/nodemon app.js

  # db:
  #   image: mongo:4.1.8-xenial
  #   container_name: db
  #   restart: unless-stopped
  #   env_file: .env
  #   environment:
  #     - MONGO_INITDB_ROOT_USERNAME=$MONGO_USERNAME
  #     - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASSWORD
  #   volumes:  
  #     - dbdata:/data/db   
  #   networks:
  #     - app-network

networks:
  app-network:
    driver: bridge

volumes:
  # dbdata:
  node_modules: